version: "3.7"
services:
  influxdb:
    image: influxdb
    volumes: 
      - "./influxdb-data:/var/lib/influxdb"
    environment:
      INFLUXDB_USER: "hacktober_collector"
      INFLUXDB_DB: "hacktober_metrics"
      INFLUXDB_USER_PASSWORD: "${INFLUXDB_USER_PASSWORD}"
  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
    ports:
      - "3000:3000"
    volumes:
      - "./grafana-data:/var/lib/grafana"
    